pipeline:
    name: Complex - Parallel
    identifier: Complex_Parallel
    projectIdentifier: RobotShop
    orgIdentifier: default
    description: Complex Deployment using Parallel Stages
    tags:
        parallel: ""
        complex: ""
        microservices: ""
    stages:
        - stage:
              name: Deploy MySql
              identifier: Deploy_MySql
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: mysql
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: mysql_manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.Github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/<+service.name>/templates
                                                    repoName: robot-shop
                                                    branch: master
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: mysql_values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.Github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/<+service.name>/values.yaml
                                                    repoName: robot-shop
                                                    branch: master
                              artifacts:
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: org.Dockerhub
                                          imagePath: robotshop/rs-mysql-db
                                          tag: latest
                  infrastructure:
                      environmentRef: staging
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKE
                              namespace: staging
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: Deploy MongoDB
              identifier: Deploy_MongoDB
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: mongodb
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: mongodb_manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.Github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/<+service.name>/templates
                                                    repoName: robot-shop
                                                    branch: master
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: mongodb_values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: org.Github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/<+service.name>/values.yaml
                                                    repoName: robot-shop
                                                    branch: master
                              artifacts:
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: org.Dockerhub
                                          imagePath: robotshop/rs-mongodb
                                          tag: latest
                  infrastructure:
                      environmentRef: staging
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKE
                              namespace: staging
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
