name: <+service.name>
replicas: 1

image: <+artifact.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: ClusterIP

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 3306
serviceTargetPort: 3306